namespace ModelCollections.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class init : DbMigration
    {
        public override void Up()
        {
//            CreateTable(
//                "dbo.PCM010",
//                c => new
//                    {
//                        PCM01_NO = c.String(nullable: false, maxLength: 10, fixedLength: true, unicode: false),
//                        DIE_NO = c.String(nullable: false, maxLength: 10, fixedLength: true, unicode: false),
//                        DIE_NAME = c.String(nullable: false, maxLength: 45, fixedLength: true, unicode: false),
//                        CUST_NO = c.String(nullable: false, maxLength: 10, fixedLength: true, unicode: false),
//                        TON = c.String(nullable: false, maxLength: 10, fixedLength: true, unicode: false),
//                        TON2 = c.String(nullable: false, maxLength: 10, fixedLength: true, unicode: false),
//                        REMARK = c.String(nullable: false, unicode: false, storeType: "text"),
//                        MDC = c.String(nullable: false, maxLength: 40, fixedLength: true, unicode: false),
//                        W_DIE = c.String(nullable: false, maxLength: 6, fixedLength: true, unicode: false),
//                        PROD_MTRL = c.String(nullable: false, maxLength: 10, fixedLength: true, unicode: false),
//                        DESIGNER = c.String(nullable: false, maxLength: 8, fixedLength: true, unicode: false),
//                        NAME2 = c.String(nullable: false, maxLength: 10, fixedLength: true, unicode: false),
//                        THICK = c.String(nullable: false, maxLength: 6, fixedLength: true, unicode: false),
//                        PITCH = c.String(nullable: false, maxLength: 6, fixedLength: true, unicode: false),
//                        WIDE = c.String(nullable: false, maxLength: 6, fixedLength: true, unicode: false),
//                        MTRL = c.String(nullable: false, maxLength: 10, fixedLength: true, unicode: false),
//                        HIGH = c.String(nullable: false, maxLength: 6, fixedLength: true, unicode: false),
//                        WEIGHT_1 = c.String(nullable: false, maxLength: 6, fixedLength: true, unicode: false),
//                        WEIGHT_U = c.String(nullable: false, maxLength: 6, fixedLength: true, unicode: false),
//                        CUST_DRAW = c.String(nullable: false, maxLength: 20, fixedLength: true, unicode: false),
//                        SET1 = c.Decimal(nullable: false, precision: 10, scale: 0),
//                        CAV = c.Decimal(nullable: false, precision: 8, scale: 0),
//                        INSERT1 = c.String(nullable: false, maxLength: 15, fixedLength: true, unicode: false),
//                        INSERT2 = c.String(nullable: false, maxLength: 15, fixedLength: true, unicode: false),
//                        SHRINK = c.Decimal(nullable: false, precision: 11, scale: 3),
//                        PHOTO = c.String(nullable: false, maxLength: 100, fixedLength: true, unicode: false),
//                        MODEL = c.String(nullable: false, maxLength: 15, fixedLength: true, unicode: false),
//                        DIETYPE = c.String(nullable: false, maxLength: 20, fixedLength: true, unicode: false),
//                        EDITION = c.String(nullable: false, maxLength: 3, fixedLength: true, unicode: false),
//                        BASE = c.String(nullable: false, maxLength: 15, fixedLength: true, unicode: false),
//                        TYPE_A = c.String(nullable: false, maxLength: 4, fixedLength: true, unicode: false),
//                        YM_NAME = c.String(nullable: false, maxLength: 45, fixedLength: true, unicode: false),
//                        TEST_NO = c.String(nullable: false, maxLength: 3, fixedLength: true, unicode: false),
//                        MDC2 = c.String(nullable: false, maxLength: 30, fixedLength: true, unicode: false),
//                        WEIGHT = c.Decimal(nullable: false, precision: 20, scale: 2),
//                        BROKER = c.String(nullable: false, maxLength: 16, fixedLength: true, unicode: false),
//                        OUT_PORT = c.String(nullable: false, maxLength: 16, fixedLength: true, unicode: false),
//                        PUR_CHK = c.String(nullable: false, maxLength: 1, fixedLength: true, unicode: false),
//                        OK_CHK = c.String(nullable: false, maxLength: 1, fixedLength: true, unicode: false),
//                        PAUSE = c.String(nullable: false, maxLength: 1, fixedLength: true, unicode: false),
//                        CAM_OK = c.String(nullable: false, maxLength: 8, fixedLength: true, unicode: false),
//                        INSERT_OK = c.String(nullable: false, maxLength: 10, fixedLength: true, unicode: false),
//                        CAM_DESI = c.String(nullable: false, maxLength: 8, fixedLength: true, unicode: false),
//                        INSERT_PR = c.String(nullable: false, maxLength: 10, fixedLength: true, unicode: false),
//                        CAM_PR = c.String(nullable: false, maxLength: 10, fixedLength: true, unicode: false),
//                        INSERT3 = c.String(nullable: false, maxLength: 15, fixedLength: true, unicode: false),
//                        INSERT4 = c.String(nullable: false, maxLength: 15, fixedLength: true, unicode: false),
//                        OK_FLG1 = c.String(nullable: false, maxLength: 1, fixedLength: true, unicode: false),
//                        CAM_HT = c.String(nullable: false, maxLength: 8, fixedLength: true, unicode: false),
//                        BASE_OK = c.String(nullable: false, maxLength: 8, fixedLength: true, unicode: false),
//                        BASE_DESI = c.String(nullable: false, maxLength: 8, fixedLength: true, unicode: false),
//                        BASE_DWG = c.String(nullable: false, maxLength: 8, fixedLength: true, unicode: false),
//                        INS_PUR = c.String(nullable: false, maxLength: 1, fixedLength: true, unicode: false),
//                        CAD_D1 = c.String(nullable: false, maxLength: 8, fixedLength: true, unicode: false),
//                        CAD_D2 = c.String(nullable: false, maxLength: 8, fixedLength: true, unicode: false),
//                        CAD_D3 = c.String(nullable: false, maxLength: 8, fixedLength: true, unicode: false),
//                        CAD_D4 = c.String(nullable: false, maxLength: 10, fixedLength: true, unicode: false),
//                        CAD_D5 = c.String(nullable: false, maxLength: 10, fixedLength: true, unicode: false),
//                        SAMPLE = c.String(nullable: false, maxLength: 10, fixedLength: true, unicode: false),
//                        LEGEND = c.String(nullable: false, maxLength: 10, fixedLength: true, unicode: false),
//                        CAD_DAYS = c.Decimal(nullable: false, precision: 6, scale: 0),
//                        CAM_DAYS = c.Decimal(nullable: false, precision: 6, scale: 0),
//                        CAM_START = c.String(nullable: false, maxLength: 10, fixedLength: true, unicode: false),
//                        BASE_D1 = c.String(nullable: false, maxLength: 10, fixedLength: true, unicode: false),
//                        CAD_HOUR = c.Decimal(nullable: false, precision: 6, scale: 0),
//                        CAM_HOUR = c.Decimal(nullable: false, precision: 6, scale: 0),
//                        APPROVE = c.String(nullable: false, maxLength: 10, fixedLength: true, unicode: false),
//                        DATE5 = c.String(nullable: false, maxLength: 10, fixedLength: true, unicode: false),
//                        INST_D2 = c.String(nullable: false, maxLength: 10, fixedLength: true, unicode: false),
//                        PLACE = c.String(nullable: false, maxLength: 20, fixedLength: true, unicode: false),
//                        ASM_D1 = c.String(nullable: false, maxLength: 10, fixedLength: true, unicode: false),
//                        ASM_D2 = c.String(nullable: false, maxLength: 10, fixedLength: true, unicode: false),
//                        ASM_D3 = c.String(nullable: false, maxLength: 10, fixedLength: true, unicode: false),
//                        ASM_D4 = c.String(nullable: false, maxLength: 10, fixedLength: true, unicode: false),
//                        ASM_D5 = c.String(nullable: false, maxLength: 10, fixedLength: true, unicode: false),
//                        ASM_D6 = c.String(nullable: false, maxLength: 10, fixedLength: true, unicode: false),
//                        CAUSE = c.String(nullable: false, maxLength: 20, fixedLength: true, unicode: false),
//                        CR_D1 = c.String(nullable: false, maxLength: 10, fixedLength: true, unicode: false),
//                        CR_D2 = c.String(nullable: false, maxLength: 10, fixedLength: true, unicode: false),
//                        CR_D3 = c.String(nullable: false, maxLength: 10, fixedLength: true, unicode: false),
//                        CR_HR1 = c.Decimal(nullable: false, precision: 6, scale: 0),
//                        CR_HR2 = c.Decimal(nullable: false, precision: 6, scale: 0),
//                        CR_HR3 = c.Decimal(nullable: false, precision: 6, scale: 0),
//                        HD1 = c.String(nullable: false, maxLength: 6, fixedLength: true, unicode: false),
//                        HD2 = c.String(nullable: false, maxLength: 6, fixedLength: true, unicode: false),
//                        HD3 = c.String(nullable: false, maxLength: 1, fixedLength: true, unicode: false),
//                        HD4 = c.String(nullable: false, maxLength: 12, fixedLength: true, unicode: false),
//                        HD5 = c.String(nullable: false, maxLength: 12, fixedLength: true, unicode: false),
//                        BUSH_DATE = c.String(nullable: false, maxLength: 10, fixedLength: true, unicode: false),
//                        PRE_OK = c.String(nullable: false, maxLength: 10, fixedLength: true, unicode: false),
//                        ATTACHMENT = c.String(nullable: false, maxLength: 10, fixedLength: true, unicode: false),
//                        GR_D1 = c.String(nullable: false, maxLength: 10, fixedLength: true, unicode: false),
//                        GR_D2 = c.String(nullable: false, maxLength: 10, fixedLength: true, unicode: false),
//                        GR_D3 = c.String(nullable: false, maxLength: 10, fixedLength: true, unicode: false),
//                        CUST_DIENO = c.String(nullable: false, maxLength: 10, fixedLength: true, unicode: false),
//                        CUST_DROW = c.String(nullable: false, maxLength: 20, fixedLength: true, unicode: false),
//                        W_PROD = c.Decimal(nullable: false, precision: 20, scale: 0),
//                        FORWARDER = c.String(nullable: false, maxLength: 10, fixedLength: true, unicode: false),
//                        K1 = c.String(nullable: false, maxLength: 10, fixedLength: true, unicode: false),
//                        VER = c.String(nullable: false, maxLength: 5, fixedLength: true, unicode: false),
//                        PROD_MDC = c.String(nullable: false, maxLength: 40, fixedLength: true, unicode: false),
//                        RUNER = c.Decimal(nullable: false, precision: 20, scale: 0),
//                        S_W = c.Decimal(nullable: false, precision: 20, scale: 0),
//                        CS = c.String(nullable: false, maxLength: 30, fixedLength: true, unicode: false),
//                        CYCLE = c.Decimal(nullable: false, precision: 20, scale: 0),
//                        C_CAV = c.String(nullable: false, maxLength: 20, fixedLength: true, unicode: false),
//                        REMARKS = c.String(nullable: false, unicode: false, storeType: "text"),
//                        TON3 = c.String(nullable: false, maxLength: 6, fixedLength: true, unicode: false),
//                        W_CORE = c.String(nullable: false, maxLength: 8, fixedLength: true, unicode: false),
//                        W_CAV = c.String(nullable: false, maxLength: 8, fixedLength: true, unicode: false),
//                        LAST_TIME = c.String(nullable: false, maxLength: 5, fixedLength: true, unicode: false),
//                        EDITER = c.String(nullable: false, maxLength: 10, fixedLength: true, unicode: false),
//                        CTS = c.Decimal(nullable: false, precision: 11, scale: 0),
//                        YR = c.Decimal(nullable: false, precision: 11, scale: 0),
//                        PROD_NO = c.String(nullable: false, maxLength: 10, fixedLength: true, unicode: false),
//                        FILE_3D = c.String(nullable: false, maxLength: 30, fixedLength: true, unicode: false),
//                        FILE_2D = c.String(nullable: false, maxLength: 30, fixedLength: true, unicode: false),
//                        REV_3D = c.String(nullable: false, maxLength: 6, fixedLength: true, unicode: false),
//                        REV_2D = c.String(nullable: false, maxLength: 6, fixedLength: true, unicode: false),
//                        SHRINK_X = c.String(nullable: false, maxLength: 10, fixedLength: true, unicode: false),
//                        SHRINK_Y = c.String(nullable: false, maxLength: 10, fixedLength: true, unicode: false),
//                        HRS = c.String(nullable: false, maxLength: 16, fixedLength: true, unicode: false),
//                        NOZZLE = c.String(nullable: false, maxLength: 30, fixedLength: true, unicode: false),
//                        ETA_HRS = c.String(nullable: false, maxLength: 8, fixedLength: true, unicode: false),
//                        SLIDE1 = c.String(nullable: false, maxLength: 16, fixedLength: true, unicode: false),
//                        SLIDE2 = c.String(nullable: false, maxLength: 16, fixedLength: true, unicode: false),
//                        NOZ01 = c.String(nullable: false, maxLength: 50, fixedLength: true, unicode: false),
//                        NOZ02 = c.String(nullable: false, maxLength: 30, fixedLength: true, unicode: false),
//                        NOZ03 = c.String(nullable: false, maxLength: 20, fixedLength: true, unicode: false),
//                        NOZ04 = c.String(nullable: false, maxLength: 20, fixedLength: true, unicode: false),
//                        BASE_HD = c.String(nullable: false, maxLength: 12, fixedLength: true, unicode: false),
//                        NAME3 = c.String(nullable: false, maxLength: 10, fixedLength: true, unicode: false),
//                        WELD = c.String(nullable: false, maxLength: 10, fixedLength: true, unicode: false),
//                        OVERFLOW = c.Decimal(nullable: false, precision: 11, scale: 2),
//                        DIE_SOURCE = c.String(nullable: false, maxLength: 1, fixedLength: true, unicode: false),
//                        QTY3 = c.Decimal(nullable: false, precision: 11, scale: 0),
//                        OLD_QTY2 = c.Decimal(nullable: false, precision: 11, scale: 0),
//                        CUST_PROD = c.String(nullable: false, maxLength: 30, fixedLength: true, unicode: false),
//                        AMT1 = c.Decimal(nullable: false, precision: 11, scale: 0),
//                        QTY1 = c.Decimal(nullable: false, precision: 11, scale: 0),
//                        QTY2 = c.Decimal(nullable: false, precision: 11, scale: 0),
//                        MAKER = c.String(nullable: false, maxLength: 20, fixedLength: true, unicode: false),
//                        TYPE2 = c.String(nullable: false, maxLength: 1, fixedLength: true, unicode: false),
//                        TIMESTAMP = c.Binary(nullable: false, fixedLength: true, timestamp: true, storeType: "timestamp"),
//                        DATE1 = c.DateTime(),
//                        DATE2 = c.DateTime(),
//                        EXPORT = c.DateTime(),
//                        EXPORT2 = c.DateTime(),
//                        T_DATE = c.DateTime(),
//                        ETA = c.DateTime(),
//                        ETD = c.DateTime(),
//                        OK_DATE = c.DateTime(),
//                        T1_DATE = c.DateTime(),
//                        GR_OKDATE = c.DateTime(),
//                        LAST_DATE = c.DateTime(),
//                        POOP_DATE = c.DateTime(),
//                        DEL_MARK = c.String(maxLength: 1, fixedLength: true, unicode: false),
//                        UTIME = c.DateTime(),
//                    })
//                .PrimaryKey(t => new { t.PCM01_NO, t.DIE_NO, t.DIE_NAME, t.CUST_NO, t.TON, t.TON2, t.REMARK, t.MDC, t.W_DIE, t.PROD_MTRL, t.DESIGNER, t.NAME2, t.THICK, t.PITCH, t.WIDE, t.MTRL, t.HIGH, t.WEIGHT_1, t.WEIGHT_U, t.CUST_DRAW, t.SET1, t.CAV, t.INSERT1, t.INSERT2, t.SHRINK, t.PHOTO, t.MODEL, t.DIETYPE, t.EDITION, t.BASE, t.TYPE_A, t.YM_NAME, t.TEST_NO, t.MDC2, t.WEIGHT, t.BROKER, t.OUT_PORT, t.PUR_CHK, t.OK_CHK, t.PAUSE, t.CAM_OK, t.INSERT_OK, t.CAM_DESI, t.INSERT_PR, t.CAM_PR, t.INSERT3, t.INSERT4, t.OK_FLG1, t.CAM_HT, t.BASE_OK, t.BASE_DESI, t.BASE_DWG, t.INS_PUR, t.CAD_D1, t.CAD_D2, t.CAD_D3, t.CAD_D4, t.CAD_D5, t.SAMPLE, t.LEGEND, t.CAD_DAYS, t.CAM_DAYS, t.CAM_START, t.BASE_D1, t.CAD_HOUR, t.CAM_HOUR, t.APPROVE, t.DATE5, t.INST_D2, t.PLACE, t.ASM_D1, t.ASM_D2, t.ASM_D3, t.ASM_D4, t.ASM_D5, t.ASM_D6, t.CAUSE, t.CR_D1, t.CR_D2, t.CR_D3, t.CR_HR1, t.CR_HR2, t.CR_HR3, t.HD1, t.HD2, t.HD3, t.HD4, t.HD5, t.BUSH_DATE, t.PRE_OK, t.ATTACHMENT, t.GR_D1, t.GR_D2, t.GR_D3, t.CUST_DIENO, t.CUST_DROW, t.W_PROD, t.FORWARDER, t.K1, t.VER, t.PROD_MDC, t.RUNER, t.S_W, t.CS, t.CYCLE, t.C_CAV, t.REMARKS, t.TON3, t.W_CORE, t.W_CAV, t.LAST_TIME, t.EDITER, t.CTS, t.YR, t.PROD_NO, t.FILE_3D, t.FILE_2D, t.REV_3D, t.REV_2D, t.SHRINK_X, t.SHRINK_Y, t.HRS, t.NOZZLE, t.ETA_HRS, t.SLIDE1, t.SLIDE2, t.NOZ01, t.NOZ02, t.NOZ03, t.NOZ04, t.BASE_HD, t.NAME3, t.WELD, t.OVERFLOW, t.DIE_SOURCE, t.QTY3, t.OLD_QTY2, t.CUST_PROD, t.AMT1, t.QTY1, t.QTY2, t.MAKER, t.TYPE2, t.TIMESTAMP });
//            
//            CreateTable(
//                "dbo.PUR010",
//                c => new
//                    {
//                        CUST_NO = c.String(nullable: false, maxLength: 10, fixedLength: true, unicode: false),
//                        SUBNAME = c.String(nullable: false, maxLength: 10, fixedLength: true, unicode: false),
//                        NAME = c.String(nullable: false, maxLength: 60, fixedLength: true, unicode: false),
//                        TEL1 = c.String(nullable: false, maxLength: 20, fixedLength: true, unicode: false),
//                        TEL2 = c.String(nullable: false, maxLength: 20, fixedLength: true, unicode: false),
//                        FAX1 = c.String(nullable: false, maxLength: 20, fixedLength: true, unicode: false),
//                        FAX2 = c.String(nullable: false, maxLength: 20, fixedLength: true, unicode: false),
//                        CONTACTER1 = c.String(nullable: false, maxLength: 20, fixedLength: true, unicode: false),
//                        CONTACTER2 = c.String(nullable: false, maxLength: 20, fixedLength: true, unicode: false),
//                        ADDR1 = c.String(nullable: false, unicode: false, storeType: "text"),
//                        PAY_TYPE = c.String(nullable: false, maxLength: 20, fixedLength: true, unicode: false),
//                        IN_TYPE = c.String(nullable: false, maxLength: 15, fixedLength: true, unicode: false),
//                        ITEM = c.String(nullable: false, maxLength: 50, fixedLength: true, unicode: false),
//                        REMARK = c.String(nullable: false, unicode: false, storeType: "text"),
//                        EMAIL = c.String(nullable: false, maxLength: 50, fixedLength: true, unicode: false),
//                        HTTP = c.String(nullable: false, maxLength: 40, fixedLength: true, unicode: false),
//                        BIL_NO = c.String(nullable: false, maxLength: 3, fixedLength: true, unicode: false),
//                        SEL_FLG = c.String(nullable: false, maxLength: 1, fixedLength: true, unicode: false),
//                        ACCT_NO = c.String(nullable: false, maxLength: 30, fixedLength: true, unicode: false),
//                        EMP_QTY = c.Decimal(nullable: false, precision: 20, scale: 0),
//                        AMT1 = c.Decimal(nullable: false, precision: 20, scale: 0),
//                        AREA = c.Decimal(nullable: false, precision: 20, scale: 0),
//                        APPRAISE = c.String(nullable: false, maxLength: 1, fixedLength: true, unicode: false),
//                        ID_NO = c.String(nullable: false, maxLength: 10, fixedLength: true, unicode: false),
//                        ADDR2 = c.String(nullable: false, maxLength: 50, fixedLength: true, unicode: false),
//                        R_TAX = c.Decimal(nullable: false, precision: 7, scale: 0),
//                        PAY_DAYS = c.Decimal(nullable: false, precision: 7, scale: 0),
//                        CAL_NAME = c.String(nullable: false, maxLength: 10, fixedLength: true, unicode: false),
//                        BANK_NO = c.String(nullable: false, maxLength: 10, fixedLength: true, unicode: false),
//                        APP_CHK = c.String(nullable: false, maxLength: 1, fixedLength: true, unicode: false),
//                        BANK_NA = c.String(nullable: false, maxLength: 40, fixedLength: true, unicode: false),
//                        CONN_TYPE = c.String(nullable: false, maxLength: 1, fixedLength: true, unicode: false),
//                        MOD_NAME = c.String(nullable: false, maxLength: 12, fixedLength: true, unicode: false),
//                        TYPE2 = c.String(nullable: false, maxLength: 1, fixedLength: true, unicode: false),
//                        ACC_TYPE1 = c.String(nullable: false, maxLength: 30, fixedLength: true, unicode: false),
//                        INV_TYPE1 = c.String(nullable: false, maxLength: 10, fixedLength: true, unicode: false),
//                        PAY_TYPE1 = c.String(nullable: false, maxLength: 10, fixedLength: true, unicode: false),
//                        CHK_EMP = c.String(nullable: false, maxLength: 12, fixedLength: true, unicode: false),
//                        DISCOUNT = c.Decimal(nullable: false, precision: 11, scale: 1),
//                        REMARK2 = c.String(nullable: false, unicode: false, storeType: "text"),
//                        TIMESTAMP = c.Binary(nullable: false, fixedLength: true, timestamp: true, storeType: "timestamp"),
//                        DATE1 = c.DateTime(),
//                        APP_DATE = c.DateTime(),
//                        DATE2 = c.DateTime(),
//                        MOD_DATE = c.DateTime(),
//                        DEL_MARK = c.String(maxLength: 1, fixedLength: true, unicode: false),
//                        UTIME = c.DateTime(),
//                    })
//                .PrimaryKey(t => new { t.CUST_NO, t.SUBNAME, t.NAME, t.TEL1, t.TEL2, t.FAX1, t.FAX2, t.CONTACTER1, t.CONTACTER2, t.ADDR1, t.PAY_TYPE, t.IN_TYPE, t.ITEM, t.REMARK, t.EMAIL, t.HTTP, t.BIL_NO, t.SEL_FLG, t.ACCT_NO, t.EMP_QTY, t.AMT1, t.AREA, t.APPRAISE, t.ID_NO, t.ADDR2, t.R_TAX, t.PAY_DAYS, t.CAL_NAME, t.BANK_NO, t.APP_CHK, t.BANK_NA, t.CONN_TYPE, t.MOD_NAME, t.TYPE2, t.ACC_TYPE1, t.INV_TYPE1, t.PAY_TYPE1, t.CHK_EMP, t.DISCOUNT, t.REMARK2, t.TIMESTAMP });
//            
//            CreateTable(
//                "dbo.PUR070",
//                c => new
//                    {
//                        PUR07_NO = c.String(nullable: false, maxLength: 10, fixedLength: true, unicode: false),
//                        CUST_NO = c.String(nullable: false, maxLength: 10, fixedLength: true, unicode: false),
//                        JOB_NO = c.String(nullable: false, maxLength: 10, fixedLength: true, unicode: false),
//                        DIE_NO = c.String(nullable: false, maxLength: 20, fixedLength: true, unicode: false),
//                        SUB_NO = c.String(nullable: false, maxLength: 20, fixedLength: true, unicode: false),
//                        QTY1 = c.Decimal(nullable: false, precision: 20, scale: 2),
//                        SPECF = c.String(nullable: false, maxLength: 50, fixedLength: true, unicode: false),
//                        MD_NO = c.String(nullable: false, maxLength: 3, fixedLength: true, unicode: false),
//                        MD_NA = c.String(nullable: false, maxLength: 30, fixedLength: true, unicode: false),
//                        REMARK1 = c.String(nullable: false, unicode: false, storeType: "text"),
//                        TIME1 = c.Decimal(nullable: false, precision: 20, scale: 2),
//                        DAYS = c.Decimal(nullable: false, precision: 20, scale: 2),
//                        CHK_FLG = c.String(nullable: false, maxLength: 1, fixedLength: true, unicode: false),
//                        OK_FLG = c.String(nullable: false, maxLength: 1, fixedLength: true, unicode: false),
//                        PLACE2 = c.String(nullable: false, maxLength: 20, fixedLength: true, unicode: false),
//                        PLACE = c.String(nullable: false, maxLength: 20, fixedLength: true, unicode: false),
//                        PUR03_NO = c.String(nullable: false, maxLength: 10, fixedLength: true, unicode: false),
//                        PSS02_NO = c.String(nullable: false, maxLength: 10, fixedLength: true, unicode: false),
//                        PUR03_SEQ = c.String(nullable: false, maxLength: 10, fixedLength: true, unicode: false),
//                        PUB04_NO = c.String(nullable: false, maxLength: 10, fixedLength: true, unicode: false),
//                        TIMESTAMP = c.Binary(nullable: false, fixedLength: true, timestamp: true, storeType: "timestamp"),
//                        DATE0 = c.DateTime(),
//                        DATE_A = c.DateTime(),
//                        DATE_B = c.DateTime(),
//                        DATE1 = c.DateTime(),
//                        DATE2 = c.DateTime(),
//                        DATE3 = c.DateTime(),
//                        DATE4 = c.DateTime(),
//                        DATE_C = c.DateTime(),
//                        DEL_MARK = c.String(maxLength: 1, fixedLength: true, unicode: false),
//                        UTIME = c.DateTime(),
//                    })
//                .PrimaryKey(t => new { t.PUR07_NO, t.CUST_NO, t.JOB_NO, t.DIE_NO, t.SUB_NO, t.QTY1, t.SPECF, t.MD_NO, t.MD_NA, t.REMARK1, t.TIME1, t.DAYS, t.CHK_FLG, t.OK_FLG, t.PLACE2, t.PLACE, t.PUR03_NO, t.PSS02_NO, t.PUR03_SEQ, t.PUB04_NO, t.TIMESTAMP });
//            
//            CreateTable(
//                "dbo.SAL010",
//                c => new
//                    {
//                        CUST_NO = c.String(nullable: false, maxLength: 10, fixedLength: true, unicode: false),
//                        SUBNAME = c.String(nullable: false, maxLength: 12, fixedLength: true, unicode: false),
//                        NAME = c.String(nullable: false, maxLength: 60, fixedLength: true, unicode: false),
//                        COUNTRY = c.String(nullable: false, maxLength: 12, fixedLength: true, unicode: false),
//                        ZIP = c.String(nullable: false, maxLength: 6, fixedLength: true, unicode: false),
//                        ADDR1 = c.String(nullable: false, unicode: false, storeType: "text"),
//                        ADDR2 = c.String(nullable: false, unicode: false, storeType: "text"),
//                        BOSS = c.String(nullable: false, maxLength: 28, fixedLength: true, unicode: false),
//                        CONTACTER = c.String(nullable: false, maxLength: 28, fixedLength: true, unicode: false),
//                        TEL1 = c.String(nullable: false, maxLength: 20, fixedLength: true, unicode: false),
//                        FAX = c.String(nullable: false, maxLength: 20, fixedLength: true, unicode: false),
//                        SEL_FLG = c.String(nullable: false, maxLength: 1, fixedLength: true, unicode: false),
//                        CLOSE_DATE = c.Decimal(nullable: false, precision: 4, scale: 0),
//                        TAX_R = c.Decimal(nullable: false, precision: 7, scale: 3),
//                        TAX_R1 = c.Decimal(nullable: false, precision: 7, scale: 3),
//                        BANK_NA = c.String(nullable: false, maxLength: 30, fixedLength: true, unicode: false),
//                        BANK_ACCNO = c.String(nullable: false, maxLength: 20, fixedLength: true, unicode: false),
//                        INV_ID = c.String(nullable: false, maxLength: 15, fixedLength: true, unicode: false),
//                        ACCT_NO = c.String(nullable: false, maxLength: 8, fixedLength: true, unicode: false),
//                        HTTP = c.String(nullable: false, maxLength: 30, fixedLength: true, unicode: false),
//                        BIL_NO = c.String(nullable: false, maxLength: 3, fixedLength: true, unicode: false),
//                        E_MAIL = c.String(nullable: false, maxLength: 30, fixedLength: true, unicode: false),
//                        MEMO1 = c.String(nullable: false, unicode: false, storeType: "text"),
//                        SERVICE = c.String(nullable: false, maxLength: 28, fixedLength: true, unicode: false),
//                        CUST_TYPE = c.String(nullable: false, maxLength: 8, fixedLength: true, unicode: false),
//                        TYPE_A = c.String(nullable: false, maxLength: 6, fixedLength: true, unicode: false),
//                        TRADE = c.String(nullable: false, maxLength: 30, fixedLength: true, unicode: false),
//                        CHK_CASH = c.Boolean(nullable: false),
//                        DAY1 = c.String(nullable: false, maxLength: 2, fixedLength: true, unicode: false),
//                        TAX_TYPE = c.String(nullable: false, maxLength: 10, fixedLength: true, unicode: false),
//                        DOWS = c.String(nullable: false, maxLength: 2, fixedLength: true, unicode: false),
//                        REMARK01 = c.String(nullable: false, maxLength: 100, fixedLength: true, unicode: false),
//                        TYPE2 = c.String(nullable: false, maxLength: 1, fixedLength: true, unicode: false),
//                        SALE_NAME = c.String(nullable: false, maxLength: 16, fixedLength: true, unicode: false),
//                        MARKS = c.String(nullable: false, unicode: false, storeType: "text"),
//                        MOD_NAME = c.String(nullable: false, maxLength: 12, fixedLength: true, unicode: false),
//                        TIMESTAMP = c.Binary(nullable: false, fixedLength: true, timestamp: true, storeType: "timestamp"),
//                        DATE1 = c.DateTime(),
//                        DATE2 = c.DateTime(),
//                        DATE3 = c.DateTime(),
//                        MOD_DATE = c.DateTime(),
//                        DEL_MARK = c.String(maxLength: 1, fixedLength: true, unicode: false),
//                        UTIME = c.DateTime(),
//                    })
//                .PrimaryKey(t => new { t.CUST_NO, t.SUBNAME, t.NAME, t.COUNTRY, t.ZIP, t.ADDR1, t.ADDR2, t.BOSS, t.CONTACTER, t.TEL1, t.FAX, t.SEL_FLG, t.CLOSE_DATE, t.TAX_R, t.TAX_R1, t.BANK_NA, t.BANK_ACCNO, t.INV_ID, t.ACCT_NO, t.HTTP, t.BIL_NO, t.E_MAIL, t.MEMO1, t.SERVICE, t.CUST_TYPE, t.TYPE_A, t.TRADE, t.CHK_CASH, t.DAY1, t.TAX_TYPE, t.DOWS, t.REMARK01, t.TYPE2, t.SALE_NAME, t.MARKS, t.MOD_NAME, t.TIMESTAMP });
//            
        }
        
        public override void Down()
        {
//            DropTable("dbo.SAL010");
//            DropTable("dbo.PUR070");
//            DropTable("dbo.PUR010");
//            DropTable("dbo.PCM010");
        }
    }
}
